<?php


namespace App\Models;


use Illuminate\Database\Eloquent\Model;

class Benefit extends Model
{
    protected $table = 'benefit';
    protected $primaryKey = 'id';
    public $timestamps = false;

    protected $fillable = [
        'id',
        'name',
        'icono',
        'dateCreate',
        'status'
    ];



    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::creating(function ($model) {
            $model->created_at = $model->freshTimestamp();
        });
    }
}
