<?php


namespace App\Models;


use Illuminate\Database\Eloquent\Model;

class Company extends Model
{
    protected $table = 'company';
    protected $primaryKey = 'id';
    public $timestamps = false;

    protected $fillable = [
        'id',
        'name',
        'icon',
        'logo',
        'phone',
        'office_latitud',
        'office_longitud',
        'office_address',
        'facebook',
        'instagram',
        'tiktok',
        'linkedin',
        'youtube'
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::creating(function ($model) {
            $model->created_at = $model->freshTimestamp();
        });
    }
}
