<?php


namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Gallery extends Model
{
    protected $table = 'gallery';
    protected $primaryKey = 'id';
    public $timestamps = false;

    protected $fillable = [
        'id',
        'name',
        'type',
        'rute',
        'nameRute',
        'typepage',
        'description',
        'dateCreate',
        'status'
    ];



    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::creating(function ($model) {
            $model->dateCreate = $model->freshTimestamp();
        });
    }

}
