<?php


namespace App\Models;


use Illuminate\Database\Eloquent\Model;

class Novelties extends Model
{
    protected $table = 'novelties';
    protected $primaryKey = 'id';
    public $timestamps = false;

    protected $fillable = [
        'id',
        'idCategory',
        'idCoverImagen',
        'title',
        'slug',
        'resume',
        'youtube',
        'text',
        'dateCreate',
        'status'
    ];



    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::creating(function ($model) {
            $model->created_at = $model->freshTimestamp();
        });
    }
}
