<?php


namespace App\Models;


use Illuminate\Database\Eloquent\Model;

class PageSeo extends Model
{
    protected $table = 'pageseo';
    protected $primaryKey = 'id';
    public $timestamps = false;

    static $rules = [
        'title' => 'required',
        'address' => 'required',
        'description' => 'required',
        'phone' => 'required',
//        'image' => 'required|image|max:2048',
        'status' => 'required',
    ];

    protected $fillable = [
        'id',
        'title',
        'address',
        'description',
        'phone',
        'status',
        'image',
        'typePage',
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::creating(function ($model) {
            $model->created_at = $model->freshTimestamp();
        });
    }
}
