<?php


namespace App\Models;


use Illuminate\Database\Eloquent\Model;

class PageSeo extends Model
{
    protected $table = 'pageseo';
    protected $primaryKey = 'id';
    public $timestamps = false;

    protected $fillable = [
        'id',
        'title',
        'address',
        'description',
        'phone',
        'status',
        'typePage',
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::creating(function ($model) {
            $model->created_at = $model->freshTimestamp();
        });
    }
}
