<?php


namespace App\Models;


use Illuminate\Database\Eloquent\Model;

class Picture extends Model
{
    protected $table = 'picture';
    protected $primaryKey = 'id';
    public $timestamps = false;

    protected $fillable = [
        'id',
        'name',
        'type',
        'rute',
        'nameRute',
        'description',
       // 'dateCreate',
        'status'
    ];



    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::creating(function ($model) {
            $model->dateCreate = $model->freshTimestamp();
        });
    }
}
