<?php


namespace App\Models;


use Illuminate\Database\Eloquent\Model;

class Property extends Model
{
    protected $table = 'property';
    protected $primaryKey = 'id';
    public $timestamps = false;

    protected $fillable = [
        'id',
        'idCategory',
        'idUser',
        'name',
        'slug',
        'description',
        'youtube',
        'idPictureCover',
        'initialFeeSoles',
        'initialFeeDollars',
        'spotPriceSoles',
        'cashPriceDollars',
        'monthlyFees',
        'idNovelty',
        'latitude',
        'longitude',
        'officeAddress',
        'projectAddress',
        'phone',
        'dateCreate',
        'status',
        'idColor',
        'province',
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::creating(function ($model) {
            $model->created_at = $model->freshTimestamp();
        });
    }
}
