<?php


namespace App\Models;


use Illuminate\Database\Eloquent\Model;

class Property extends Model
{

    static $rules = [
        'idCategory' => 'required',
        'idUser' => 'required',
        'name' => 'required',
        'slug' => 'required',
        'description' => 'required',
        'youtube' => 'required',
        'idPictureCover' => 'required',
        'initialFeeSoles' => 'required',
        'initialFeeDollars' => 'required',
        'spotPriceSoles' => 'required',
        'cashPriceDollars' => 'required',
        'monthlyFees' => 'required',
        'idNovelty' => 'required',
        'latitude' => 'required',
        'longitude' => 'required',
        'officeAddress' => 'required',
        'projectAddress' => 'required',
        'phone' => 'required',
        'dateCreate' => 'required',
        'status' => 'required',
        'idColor' => 'required',
        'idPictureCoverPage' => 'required',
        'idIconMap' => 'required',
        'province' => 'required',
    ];


    protected $table = 'property';
    protected $primaryKey = 'id';
    public $timestamps = false;

    protected $fillable = [
        'id',
        'idCategory',
        'idUser',
        'name',
        'slug',
        'description',
        'youtube',
        'idPictureCover',
        'initialFeeSoles',
        'initialFeeDollars',
        'spotPriceSoles',
        'cashPriceDollars',
        'monthlyFees',
        'idNovelty',
        'latitude',
        'longitude',
        'officeAddress',
        'projectAddress',
        'phone',
        'dateCreate',
        'status',
        'idColor',
        'province',
    ];

//    public static function create(array $all)
//    {
//    }

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::creating(function ($model) {
            $model->dateCreate = $model->freshTimestamp();
        });
    }
}
